/*
 * Copyright ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.hyperledger.besu.plugin.data;

import org.hyperledger.besu.datatypes.LogsBloomFilter;

import java.util.List;
import java.util.Optional;

import org.apache.tuweni.bytes.Bytes;

/** A transaction receipt, containing information pertaining to a transaction execution. */
public interface TransactionReceipt {
  /**
   * Returns the total amount of gas consumed in the block after the transaction has been processed.
   *
   * @return the total amount of gas consumed in the block after the transaction has been processed
   */
  long getCumulativeGasUsed();

  /**
   * Returns the logs generated by the transaction.
   *
   * @return the logs generated by the transaction
   */
  List<? extends Log> getLogs();

  /**
   * Returns the Bytes for the logs generated by the transaction
   *
   * @return the Bytes for the logs generated by the transaction
   */
  LogsBloomFilter getBloomFilter();

  /**
   * Returns the status code for the status-encoded transaction receipt
   *
   * @return the status code if the transaction receipt is status-encoded; otherwise {@code -1}
   */
  int getStatus();

  /**
   * Returns the ABI-encoded revert reason for the failed transaction (if applicable)
   *
   * @return the ABI-encoded revert reason for the failed transaction (if applicable)
   */
  Optional<Bytes> getRevertReason();

  /**
   * Returns the gas spent by this transaction (post-refund, what the user pays). This field is only
   * present for Amsterdam+ (EIP-7778) receipts.
   *
   * <p>In Amsterdam+, cumulativeGasUsed represents pre-refund gas (for block accounting), while
   * gasSpent represents post-refund gas (what users actually pay).
   *
   * @return the gas spent if present (Amsterdam+), otherwise empty (pre-Amsterdam)
   */
  default Optional<Long> getGasSpent() {
    return Optional.empty();
  }
}
