#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

caliper:
    report:
        path: 'report-onchain.html'
    benchconfig: caliper-benchconfig.yaml
    networkconfig: caliper-networkconfig.json
    txupdatetime: 500
    workspace: ./
    logging:
        template: '%timestamp%%level%%module%%message%%metadata%'
        formats:
            timestamp: 'YYYY.MM.DD-HH:mm:ss.SSS ZZ'
            label: false
            json: false
            pad: true
            align: false
            attributeformat:
                level: ' %attribute%'
                module: ' [%attribute%] '
                metadata: ' (%attribute%)'
            colorize:
                all: true
                colors:
                    info: green
                    error: red
                    warn: yellow
                    debug: grey
        targets:
            console:
                target: console
                enabled: true
                options:
                    level: info
            file:
                target: file
                enabled: false
