name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    container: tmio/besu-build:1.0
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJava compileTestJava assemble
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: besu-zip
          path: build/distributions/*.zip
  testWindows:
    runs-on: windows-latest
    needs: assemble
    timeout-minutes: 10
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Download zip
        uses: actions/download-artifact@v3.1.0
        with:
          name: besu-zip
      - name: test Besu
        run: |
          cd build/distributions
          unzip besu-*.zip -d besu-tmp
          cd besu-tmp
          mv besu-* ../besu
          cd ..
          besu\bin\besu.bat --help
          besu\bin\besu.bat --version
  test:
    runs-on: ubuntu-latest
    needs: assemble
    container: tmio/besu-build:1.0
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: build/reports/
  integration-test:
    runs-on: ubuntu-latest
    needs: assemble
    container: tmio/besu-build:1.0
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: integrationTest
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-reports
          path: build/reports/
  javadoc:
    runs-on: ubuntu-latest
    container: tmio/besu-build:1.0
    needs: integration-test
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: javadoc-reports
          path: build/reports/
  compileJmh:
    runs-on: ubuntu-latest
    container: tmio/besu-build:1.0
    needs: integration-test
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJmh
  referenceTest:
    runs-on: ubuntu-latest
    container: tmio/besu-build:1.0
    needs: integration-test
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: referenceTest