# Hyperledger Repolinter Action
name: Repolinter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: hyperledger-tools.jfrog.io/repolinter:0.10.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Repo
        run: bundle exec /app/bin/repolinter.js --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/master/repo_structure/repolint.json --format markdown
