# SPDX-License-Identifier: Apache-2.0
# Hyperledger Repolinter Action
name: Repolinter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: [besu,Linux,self-hosted,X64]
    container: ghcr.io/todogroup/repolinter:v0.10.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Repo
        run: bundle exec /app/bin/repolinter.js --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/main/repo_structure/repolint.json --format markdown
      - name: Cleanup file permissions created by docker user
        run: |
          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          chown -R "$USER_ID:$GROUP_ID" .