# SPDX-License-Identifier: Apache-2.0
# Hyperledger Repolinter Action
name: repolinter

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/todogroup/repolinter:v0.11.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint Repo
        run: bundle exec /app/bin/repolinter.js --rulesetUrl https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/main/repo_structure/repolint.json --format markdown
