/*
 * Copyright contributors to Besu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.hyperledger.besu.ethereum.vm.operations;

import static org.mockito.Mockito.mock;

import org.hyperledger.besu.datatypes.Address;
import org.hyperledger.besu.datatypes.Hash;
import org.hyperledger.besu.datatypes.Wei;
import org.hyperledger.besu.evm.code.CodeV0;
import org.hyperledger.besu.evm.frame.BlockValues;
import org.hyperledger.besu.evm.frame.MessageFrame;
import org.hyperledger.besu.evm.worldstate.WorldUpdater;

import java.util.Random;
import java.util.function.BiPredicate;
import java.util.function.Predicate;
import java.util.function.Supplier;

import org.apache.tuweni.bytes.Bytes;
import org.apache.tuweni.bytes.Bytes32;
import org.apache.tuweni.units.bigints.UInt256;

public class BenchmarkHelper {
  public static MessageFrame createMessageCallFrame() {
    return MessageFrame.builder()
        .worldUpdater(mock(WorldUpdater.class))
        .originator(Address.ZERO)
        .gasPrice(Wei.ONE)
        .blobGasPrice(Wei.ONE)
        .blockValues(mock(BlockValues.class))
        .miningBeneficiary(Address.ZERO)
        .blockHashLookup((__, ___) -> Hash.ZERO)
        .type(MessageFrame.Type.MESSAGE_CALL)
        .initialGas(Long.MAX_VALUE)
        .address(Address.ZERO)
        .contract(Address.ZERO)
        .inputData(Bytes32.ZERO)
        .sender(Address.ZERO)
        .value(Wei.ZERO)
        .apparentValue(Wei.ZERO)
        .code(CodeV0.EMPTY_CODE)
        .completer(__ -> {})
        .build();
  }

  public static MessageFrame createMessageCallFrameWithCallData(final Bytes callData) {
    return MessageFrame.builder()
        .worldUpdater(mock(WorldUpdater.class))
        .originator(Address.ZERO)
        .gasPrice(Wei.ONE)
        .blobGasPrice(Wei.ONE)
        .blockValues(mock(BlockValues.class))
        .miningBeneficiary(Address.ZERO)
        .blockHashLookup((__, ___) -> Hash.ZERO)
        .type(MessageFrame.Type.MESSAGE_CALL)
        .initialGas(Long.MAX_VALUE)
        .address(Address.ZERO)
        .contract(Address.ZERO)
        .inputData(callData)
        .sender(Address.ZERO)
        .value(Wei.ZERO)
        .apparentValue(Wei.ZERO)
        .code(CodeV0.EMPTY_CODE)
        .completer(__ -> {})
        .build();
  }

  /**
   * Fills an array with random 32-byte values.
   *
   * @param pool the destination array
   */
  public static void fillPool(final Bytes[] pool) {
    final Random random = new Random();
    fillPool(pool, () -> 1 + random.nextInt(32)); // [1, 32]
  }

  /**
   * Fills an array with random byte values of the specified size.
   *
   * @param pool the destination array
   * @param sizeSupplier size of the Bytes
   */
  public static void fillPool(final Bytes[] pool, final Supplier<Integer> sizeSupplier) {
    final Random random = new Random();
    for (int i = 0; i < pool.length; i++) {
      final byte[] a = new byte[sizeSupplier.get()];
      random.nextBytes(a);
      pool[i] = Bytes.wrap(a);
    }
  }

  /**
   * FIlls an array with random byte values of the specified size that fulfil the specified
   * condition.
   *
   * @param pool the destination array
   * @param sizeSupplier size of the Bytes
   * @param condition predicate for whether to add value to the pool
   */
  public static void fillPool(
      final Bytes[] pool, final Supplier<Integer> sizeSupplier, final Predicate<Bytes> condition) {
    final Random random = new Random();
    for (int i = 0; i < pool.length; i++) {
      final byte[] arrayA = new byte[sizeSupplier.get()];
      Bytes a;
      do {
        random.nextBytes(arrayA);
        a = Bytes.wrap(arrayA);
      } while (!condition.test(a));
      pool[i] = a;
    }
  }

  /**
   * Fill 2 arrays with random byte values that have a relationship between elements of a specified
   * size.
   *
   * @param aPool destination array for pool a
   * @param bPool destination array for pool b
   * @param aSizeSupplier size of the Bytes for pool a
   * @param bSizeSupplier size of the Bytes for pool b
   * @param condition whether to include generated bytes in pools
   */
  public static void fillPools(
      final Bytes[] aPool,
      final Bytes[] bPool,
      final Supplier<Integer> aSizeSupplier,
      final Supplier<Integer> bSizeSupplier,
      final BiPredicate<Bytes, Bytes> condition) {

    if (aPool.length != bPool.length) {
      throw new IllegalArgumentException("pools should have same length");
    }

    final Random random = new Random();
    for (int i = 0; i < aPool.length; i++) {
      final int aSize = aSizeSupplier.get();
      final int bSize = bSizeSupplier.get();
      Bytes a, b;
      do {
        final byte[] arrayA = new byte[aSize];
        final byte[] arrayB = new byte[bSize];
        random.nextBytes(arrayA);
        random.nextBytes(arrayB);
        a = Bytes.wrap(arrayA);
        b = Bytes.wrap(arrayB);
      } while (!condition.test(a, b));
      aPool[i] = a;
      bPool[i] = b;
    }
  }

  static Bytes createCallData(final int size, final boolean nonZero) {
    byte[] data = new byte[size];
    if (nonZero) {
      for (int i = 0; i < size; i++) {
        data[i] = (byte) (i % 256);
      }
    }
    return Bytes.wrap(data);
  }

  static void fillPoolsForCallData(
      final Bytes[] sizePool,
      final Bytes[] destOffsetPool,
      final Bytes[] srcOffsetPool,
      final int dataSize,
      final boolean fixedSrcDst) {
    for (int i = 0; i < sizePool.length; i++) {
      sizePool[i] = Bytes.wrap(UInt256.valueOf(dataSize));

      if (fixedSrcDst) {
        destOffsetPool[i] = Bytes.wrap(UInt256.valueOf(0));
        srcOffsetPool[i] = Bytes.wrap(UInt256.valueOf(0));
      } else {
        destOffsetPool[i] = Bytes.wrap(UInt256.valueOf((i * 32) % 1024));
        srcOffsetPool[i] = Bytes.wrap(UInt256.valueOf(i % Math.max(1, dataSize)));
      }
    }
  }
}
